metadata:
  output_path: /home/valentin/data/target/data/nnUNet_results_finetuning_v2_exp3

nnUNetTrainerFineTuningV2:
  encoder_lr: 0.01
  decoder_lr: 0.01
  seglayers_lr: 0.01
  encoder_frozen: True
  decoder_frozen: True
  n_epochs_decoder_frozen: 50
  n_epochs_encoder_frozen: 100
  pretrained_encoder_path: "/home/vincent/repos/ssl-bm/weights/cnn3d_nnunet_local_global_100ep_checkpoint.pth"
